name: Factions
main: de.prwh.factions.main.FactionsMain
version: 0.0.1
api-version: 1.16
author: Dragonisser

commands:
    factions:
      description: Welcome to Factions.
      usage: /<command>
      permission: factions
      permission-message: You don't have the permissions <permission>
      aliases: f